apiVersion: machinenativeops.io/v1
kind: RootReferenceSpec
metadata:
  annotations:
    machinenativeops.io/description: Machine-verifiable reference conventions for
      root layer
    machinenativeops.io/enforcement: strict
    machinenativeops.io/last-modified: '2025-12-21T02:00:00Z'
  labels:
    machinenativeops.io/component: reference-spec
    machinenativeops.io/tier: specs
    machinenativeops.io/version: v1.0.0
  name: root-reference-specification
  namespace: machinenativenops
spec:
  best_practices:
  - description: 跨系統引用應優先使用 URN 格式
    id: BP-REF-001
    rationale: URN 提供全域唯一性和版本控制
    title: 優先使用 URN
  - description: 使用配置引用而非硬編碼檔案路徑
    id: BP-REF-002
    rationale: 提高可移植性和可維護性
    title: 避免硬編碼路徑
  - description: 依賴聲明應包含明確的版本範圍
    id: BP-REF-003
    rationale: 避免版本衝突和不相容問題
    title: 明確版本依賴
  - description: 複雜引用關係應在註解中說明
    id: BP-REF-004
    rationale: 提高可讀性和可維護性
    title: 文檔化引用關係
  integrity_checks:
    circular_dependency:
      actions:
        on_cycle_detected: error
        report_cycle_path: true
      algorithm: depth_first_search
      description: 檢測並防止循環依賴
      enabled: true
    consistency:
      actions:
        on_mismatch: error
      check:
      - 同一模組在不同檔案中的引用必須一致
      - 版本號必須匹配
      description: 驗證引用在不同檔案間的一致性
      enabled: true
    existence:
      actions:
        on_ambiguous: warning
        on_missing: error
      description: 驗證所有引用的目標都存在
      enabled: true
      sources:
      - root.registry.modules.yaml
      - root.registry.urns.yaml
      - root.fs.map
    uniqueness:
      actions:
        on_duplicate: error
      check:
      - 同一 URN 不可指向多個實體
      - 同一模組名稱不可重複定義
      description: 驗證引用目標的唯一性
      enabled: true
  reference_field_rules:
  - description: 所有 *_ref 欄位必須使用 URN 格式
    examples:
      invalid_fields:
      - 'module_ref: governance-engine'
      valid_fields:
      - 'module_ref: urn:machinenativeops:module:governance-engine'
      - 'service_ref: urn:machinenativeops:service:trust-manager'
    field_pattern: .*_ref$
    required_format: urn
  - description: 依賴項目名稱必須使用模組引用格式
    field_pattern: ^dependencies\[\]\.name$
    required_format: module_ref
    validation:
    - 必須在 root.registry.modules.yaml 中存在
    - 不可引用自身
    - 不可形成循環依賴
  - description: 入口點必須使用絕對路徑
    field_pattern: ^entrypoint$
    required_format: file_path_ref
    validation:
    - 路徑必須存在於檔案系統映射中
    - 必須指向可執行檔案
  - description: 配置來源必須引用 root.* 配置檔
    field_pattern: ^config_source$
    required_format: config_ref
    validation:
    - 引用的配置檔必須存在
  reference_formats:
    config_ref:
      description: 配置項目引用
      examples:
        invalid:
        - config
        - root.Config
        valid:
        - root.config
        - root.modules
        - root.governance
      pattern: ^root\.[a-z][a-z0-9-]*$
    env_var_ref:
      description: 環境變數引用
      examples:
        invalid:
        - governance_mode
        - GovernanceMode
        - GOVERNANCE-MODE
        valid:
        - GOVERNANCE_MODE
        - API_KEY
        - DB_HOST
      pattern: ^[A-Z][A-Z0-9_]*$
    file_path_ref:
      description: 檔案系統路徑引用
      examples:
        invalid:
        - /Opt/MachineNativeOps/Main.py
        - opt/machinenativenops/main.py
        - /opt/machinenativenops//main.py
        valid:
        - /opt/machinenativenops/modules/governance-engine/main.py
        - /etc/machinenativenops/config.yaml
        - /var/log/machinenativenops/audit.log
      pattern: ^(/[a-z0-9_-]+)+(/[a-z0-9_.-]+)?$
    module_ref:
      description: 模組間依賴引用
      examples:
        invalid:
        - ConfigManager
        - config_manager
        - config.manager
        valid:
        - config-manager
        - logging-service
        - trust-manager
      pattern: ^[a-z][a-z0-9-]*[a-z0-9]$
    urn:
      components:
        identifier: '[a-z0-9-]+'
        namespace: machinenativeops
        scheme: urn
        type: module|service|config|policy|certificate|audit
        version: v\d+ (optional)
      description: 統一資源名稱，用於跨系統引用
      examples:
        invalid:
        - urn:axiom:module:governance-engine
        - urn:machinenativeops:Module:governance-engine
        - urn:machinenativeops:module:GovernanceEngine
        - machinenativeops:module:governance-engine
        valid:
        - urn:machinenativeops:module:governance-engine
        - urn:machinenativeops:module:governance-engine:v1
        - urn:machinenativeops:service:trust-manager
        - urn:machinenativeops:config:root-config
        - urn:machinenativeops:policy:rbac-policy
        - urn:machinenativeops:certificate:root-ca
        - urn:machinenativeops:audit:governance-audit
      pattern: ^urn:machinenativeops:(module|service|config|policy|certificate|audit):[a-z0-9-]+(:v\d+)?$
  resolution_strategy:
    file_path_resolution:
      lookup_order:
      - root.fs.map
      - filesystem
      priority: 3
      validate_existence: true
    module_resolution:
      lookup_order:
      - root.registry.modules.yaml
      - root.modules.yaml
      priority: 2
      version_matching: semver
    urn_resolution:
      cache_enabled: true
      cache_ttl: 300s
      lookup_order:
      - root.registry.urns.yaml
      - root.registry.modules.yaml
      priority: 1
  validation:
    checks:
    - description: 驗證引用格式
      enabled: true
      name: format_validation
    - description: 驗證引用目標存在
      enabled: true
      name: existence_validation
    - description: 驗證引用一致性
      enabled: true
      name: consistency_validation
    - description: 檢測循環依賴
      enabled: true
      name: circular_dependency_detection
    enabled: true
    enforcement_level: strict
    error_handling:
      on_circular_dependency: block_pr
      on_format_error: block_pr
      on_missing_reference: block_pr
      on_version_mismatch: warning
  validation_rules:
  - check: 引用的目標必須存在於註冊表中
    description: 所有引用必須可解析
    id: REF-001
    scope:
    - module_ref
    - service_ref
    - config_ref
    severity: error
  - check: 所有 URN 必須符合定義的正則表達式
    description: URN 格式必須正確
    id: REF-002
    scope:
    - urn
    severity: error
  - algorithm: topological_sort
    check: 依賴圖必須是有向無環圖 (DAG)
    description: 模組依賴不可循環
    id: REF-003
    scope:
    - dependencies
    severity: error
  - check: 引用的檔案路徑必須在 root.fs.map 中定義
    description: 檔案路徑必須存在
    id: REF-004
    scope:
    - file_path_ref
    severity: warning
  - check: 依賴版本必須滿足 semver 相容性
    description: 版本引用必須相容
    id: REF-005
    scope:
    - dependencies[].version
    severity: error
  - check: 引用的環境變數必須在配置中定義
    description: 環境變數引用必須定義
    id: REF-006
    scope:
    - env_var_ref
    severity: warning
  version: 1
status:
  conditions:
  - lastTransitionTime: '2025-12-21T02:00:00Z'
    message: Reference specification is complete and validated
    reason: SpecificationComplete
    status: 'True'
    type: Validated
  phase: Active
  statistics:
    coverage: 100%
    total_checks: 4
    total_formats: 5
    total_rules: 6
